apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: memory-nodes-alerts
  namespace: observabilidade
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: memory-nodes-alerts
      rules:
        - alert: HighMemoryUsage
          expr: >
            (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 70
          for: 5m
          labels:
            severity: warning
            channel: telegram-homelab
          annotations:
            description: "🚨 A instância *{{ $labels.instance }}* está usando {{ printf \"%.2f\" $value }}% da memória disponível!"
            summary: "Uso de Memória alto na instância {{ $labels.instance }}."
        - alert: CriticalMemoryUsage
          expr: >
            (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
          for: 2m
          labels:
            severity: critical
            channel: telegram-homelab
          annotations:
            description: "🚨 A instância *{{ $labels.instance }}* está usando {{ printf \"%.2f\" $value }}% da memória disponível!"
            summary: "Uso de Memória alto na instância {{ $labels.instance }}."